apiVersion: nhncloud.com/v1beta1
kind: Instance
metadata:
  name: ubuntu-vm
spec:
  flavorRef: "m2.c2m4"
  imageRef: "Ubuntu-20.04"
  key_name: "k8s"
  min_count: 3
  name: ubuntu_vm
  networks:
  - subnet: "bb9d5998-abb2-47ae-8144-8137fb06b0ec"
  block_device_mapping_v2:
    - delete_on_termination: 1
      destination_type: "volume"
      device_name: "vda"
      source_type: "image"
      volume_size: 30
      boot_index: 0