apiVersion: nhncloud.com/v1beta1
kind: Instance
metadata:
  name: ubuntu-vm
spec:
  flavorRef: "m2.c2m4"
  imageRef: "Ubuntu-20.04"
  key_name: "k8s"
  min_count: 2
  name: ubuntu_vm
  networks:
  - subnet: "0441c2ea-4c9d-4e89-820e-a91311ceca37"
  block_device_mapping_v2:
    - delete_on_termination: 1
      destination_type: "volume"
      device_name: "vda"
      source_type: "image"
      volume_size: 30
      boot_index: 0
